import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Layout from "@/components/layout/layout";
// Importing UI Components
import OurAdvantages from "@/components/UI/OurAdvantages/index";
import Card from "@/components/UI/LessonDetailsCard/index";
import StuffComponent from "@/components/UI/stuffComponent";
import Banner from "@/components/UI/Banner/index";
// Importing Images
import testPic from "../public/images/study-textbook.jpg";
import heroPic from "../public/images/andrea_teaching_1920.jpg";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Banner />
        <div className={styles.jumbotron}>
          <h1>
            英語ができると、
            <br />
            人生がもっと楽しくなる
          </h1>
          <p>
            クロストークは岡山市北区にある英会話スクールです。テキストで基本を学ぶことはもちろん、生きた英語で、楽しくしっかりと上達できます！思い立った今が、チャレンジのときです。英語を学んで、あなたの夢を叶えましょう！
          </p>
          <Image
            src={heroPic}
            alt="tes"
            width={800}
            height={800}
            style={{
              maxWidth: "25rem",
              height: "auto",
              backgroundPosition: "center",
            }}
          />
        </div>
        <div className={styles.section_heading}>
          <span>RESON</span>
          <p>
            CrossTalkで英語が
            <br />
            話せるようになる理由
          </p>
        </div>
        <div>
          <OurAdvantages color="red">
            少人数制で
            <br />
            会話量が多い
          </OurAdvantages>
          <OurAdvantages color="orange">
            経験豊富な
            <br />
            外国人講師
          </OurAdvantages>
          <OurAdvantages>
            アットホーム
            <br />
            な空間
          </OurAdvantages>
        </div>
        <div className={styles.section_heading}>
          <span>LESSONS</span>
          <p>
            初心者から上級者まで、それぞれのレベルに
            <br />
            合わせたレッスンプラン
          </p>
        </div>
        <Card />
        <StuffComponent />
      </main>
    </Layout>
  );
}
