import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import testPic from "../public/images/study-textbook.jpg";
import Layout from "@/components/layout/layout";
// Importing UI Components
import OurAdvantages from "@/components/UI/OurAdvantages/index";
import Card from "@/components/UI/LessonDetailsCard/index";
import BackgroundPage from "@/components/UI/ImageComponent/index";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Image
          src={testPic}
          alt="tes"
          width={1000}
          height={1000}
          style={{
            maxWidth: "30rem",
            height: "auto",
          }}
        />
        <h2 className={styles.heading}>
          CrossTalkのレッスンは英語を楽しく話すことが モットーです！
        </h2>
        <p className={styles.intro}>
          クロストークは岡山市北区にある英会話教室です。テキストで基本を学ぶことはもちろん、生きた英語で、楽しくしっかりと上達できます！思い立った今が、チャレンジのときです。英語を学んで、あなたの夢を叶えましょう！
        </p>
        <a href="/courses" className={styles.cta}>
          Explore Courses
        </a>
      </main>
      <OurAdvantages />
      <Card />
      <BackgroundPage />
    </Layout>
  );
}
